name: send msg

on:
  push:
    branches:
      - main
jobs:
  build:
    name: taiwan-index
    runs-on: ubuntu-latest
    steps:
      - env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: |
          export DATE=$(date +'%d-%m-%Y') && \
          curl "https://api.telegram.org/${TG_TOKEN}/sendMessage" \
              --data-urlencode "chat_id=-1001575225629" \
              --data-urlencode "text=[法說會資料更新](https://github.com/bangyuwen/stock7-local/blob/main/report/conference/${DATE}.md)" \
              --data-urlencode "parse_mode=markdown" \
              --data-urlencode "disable_web_page_preview=true"